spring:
  application:
    name: neta-app

  mail:
    username: ajar1996@163.com
    password: XXXXXXX
    host: smtp.163.com
    port: 25
    protocol: smtp

  datasource:
    url: jdbc:mysql://www.ajarz.icu:3306/neta_app
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
