spring:
  application:
    name: neta-app

  mail:
    username: ajar1996@163.com
    password: xxxxxxxx
    host: smtp.163.com
    port: 25
    protocol: smtp

  datasource:
    url: jdbc:mysql://xxxxxxxx:3306/neta_app?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: xxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9000